apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-exemple-platform-k8s 
spec:
  selector:
    matchLabels:
      app: app-exemple-platform-k8s
  template:
    metadata:
      labels:
        app: app-exemple-platform-k8s
    spec:
      containers:
        - image: okteto.dev/java-gradle-app-exemple-platform-k8s:1.0.0
          name: app-exemple-platform-k8s

---

apiVersion: v1
kind: Service
metadata:
  name: app-exemple-platform-k8s
spec:
  type: ClusterIP
  ports:
    - name: "app-exemple-platform-k8s"
      port: 8081
  selector:
    app: app-exemple-platform-k8s

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-exemple-platform-k8s
  annotations:
    dev.okteto.com/generate-host: app-exemple-platform-k8s
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-exemple-platform-k8s
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific